---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpatrol
spec:
  selector:
    matchLabels:
      app: smartpatrol
  template:
    metadata:
      labels:
        app: smartpatrol
    spec:
      containers:
        - name: smartpatrol
          image: gcr.io/development-03717872/smartpatrol
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: smartpatrol-lb
spec:
  type: LoadBalancer
  selector:
    app: smartpatrol
  ports:
    - port: 8000
      targetPort: 8080
