# Generated by Django 3.2.5 on 2021-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_guard', models.CharField(max_length=100)),
                ('assigned_area', models.CharField(max_length=100)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
